server:
  port: 8888
spring:
  application:
    name: demo-config-server
  profiles:
    active: git # EnvironmentRepositoryConfiguration
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/thbspan/cloud-test.git
          search-paths: /config-repo
          default-label: master # 使用的默认分支
