spring:
  application:
    name: demo01-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 28080
ribbon:
  eager-load:
    # 指定需要饥饿加载的客户端名称，服务名称
    clients:
      - ${spring.application.name}
      - demo01-provider
    enabled: true # 是否开启饥饿加载。默认为 false
