spring:
  application:
    name: zuul-application
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8888
zuul:
  servlet-path: /
  routes: # 路由配置
    route_blog:
      path: /blog/**
      url: https://blog.csdn.net
    route_oschina:
      path: /oschina/**
      url: https://www.oschina.net
    route_users:
      path: /nacos/**
      service-id: nacos-provider
