spring:
  application:
    name: zookeeper-consumer
  cloud:
    zookeeper:
      connect-string: localhost:2181
      # session 超时时间，如果<minSessionTimeout，则使用minSessionTimeout；如果>maxSessionTimeout，则使用maxSessionTimeout。
      session-timeout: 10s
      connection-timeout: 10s
      discovery:
        register: true
        root: /services
      dependency:
        enabled: true
zookeeper-provider:
  ribbon:
    NFLoadBalancerPingInterval: 2
server:
  port: 29999
