spring:
  application:
    name: openfeign-consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 28080
logging:
  level:
    # feign日志以debug方式输出的，所有这里需要设置日志级别
    com.test.cloud.openfeign.consumer.service: DEBUG

feign:
  # feign 客户端配置，对应 FeignClientProperties
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    # 更多的配置参考类 FeignClientConfiguration 中的属性
    config:
      # 全局配置
      default:
        logger-level: BASIC
      # 客户端级别配置
      openfeign-provider-demo:
        logger-level: FULL
