spring:
  application:
    name: openfeign-consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 28080
ribbon:
  # 请求的连接超时时间，单位：毫秒。默认为 1000
  ConnectTimeout: 1000
  # 请求的读取超时时间，单位：毫秒。默认为 1000
  ReadTimeout: 1000
  # 是否对所有操作都进行重试，默认为 false
  OkToRetryOnAllOperations: true
  # 对当前服务的重试次数，默认为 0 次
  MaxAutoRetries: 0
  # 重新选择服务实例的次数，默认为 1 次。注意，不包含第 1 次哈
  MaxAutoRetriesNextServer: 1
feign:
  httpclient:
    # 是否开启。默认为 true
    enabled: true
    # 最大连接数。默认为 200
    max-connections: 200
    # 每个路由的最大连接数。默认为 50。router = host + port
    max-connections-per-route: 50
