spring:
  application:
    name: eureka-server-standalone
server:
  port: 8761 # eureka-server 端口
eureka:
  client:
    register-with-eureka: false # 不注册到eureka-server
    fetch-registry: false # 不从eureka-server获取注册表
