spring:
  application:
    name: eureka-server-standalone
server:
  port: 8761 # eureka-server 端口
eureka:
  server:
    eviction-interval-timer-in-ms: 60
  instance:
    # 集群部署时，如果不配置这个属性值，那么${spring.application.name}的值必须相同
    # 如果配置了这个值，那么集群中这个属性要相同
    appname: ${spring.application.name}
    prefer-ip-address: true
    # 可以自定义hostname
    # hostname: xxxx
    lease-expiration-duration-in-seconds: 90
  client:
    # 集群部署时 register-with-eureka fetch-registry 改为true
    register-with-eureka: false # 不注册到eureka-server
    fetch-registry: false # 不从eureka-server获取注册表
    # 集群部署时，配置其他eureka的地址，实现相互注册（两两注册，假设有3个节点，这里配置其他两个的地址）
#    service-url:
#      defaultZone: http://localhost:8761/eureka
