spring:
  application:
    name: geteway-demo
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: blog-one
          uri: https://blog.csdn.net
          predicates:
            - Path=/blog
            - Weight=blog, 90
          filters:
            - StripPrefix=1
        - id: blog-two
          uri: https://www.cnblogs.com
          predicates:
            - Path=/blog
            - Weight=blog, 10
          filters:
            - StripPrefix=1
      # 与注册中心集合 DiscoveryLocatorProperties
      discovery:
        locator:
          enabled: true
          url-expression: "'lb://'+serviceId"
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8888
