spring:
  application:
    name: geteway-demo
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: search # 路由的编号
          uri: https://www.baidu.com # 路由的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/s
          filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
            - StripPrefix=1
        - id: oschina
          uri: https://www.oschina.net
          predicates:
            - Path=/oschina
          filters:
            - StripPrefix=1
        - id: blog
          uri: https://blog.csdn.net
          predicates:
            - Path=/blog
          filters:
            - StripPrefix=1
      default-filters: # 默认过滤器，如果只想给指定路由配置过滤器，可以在 spring.cloud.gateway.routes[x].filters 配置项中，进行自定义设置
        - name: Auth # 过滤器名。XXXGatewayFilterFactory XXX前缀
          args: # 过滤器的配置参数
            # 设置 token-header-name 配置项为 access-token，表示从请求 Header access-token 获得认证 Token
            # 不设置会使用默认值 token
            token-header-name: access-token
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8888
