spring:
  application:
    name: demo-provider
server:
  port: 0 # 解决随机端口问题
management:
  context-path: /manage
eureka:
  instance: # 解决随机端口问题
    instance-id: ${spring.application.name}:${random.int}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    register-with-eureka: true # 注册到 eureka-server
    fetch-registry: true # 从eureka-server获取注册表
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka-Server 地址
